-- MySQL Script generated by MySQL Workbench
-- Tue Apr  5 12:09:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema autor
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema autor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autor` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `autor` ;

-- -----------------------------------------------------
-- Table `autor`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autor`.`autor` (
  `idautor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(40) NULL,
  `prijmeni` VARCHAR(45) NULL,
  `dilo` VARCHAR(50) NULL,
  PRIMARY KEY (`idautor`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `autor`.`autor`
-- -----------------------------------------------------
START TRANSACTION;
USE `autor`;
INSERT INTO `autor`.`autor` (`idautor`, `jmeno`, `prijmeni`, `dilo`) VALUES (1, 'Jaroslav', 'Flegr', 'Milý Micíku, aneb Covid v Kocourkově');
INSERT INTO `autor`.`autor` (`idautor`, `jmeno`, `prijmeni`, `dilo`) VALUES (2, 'Božena', 'Němcová', 'Babička');
INSERT INTO `autor`.`autor` (`idautor`, `jmeno`, `prijmeni`, `dilo`) VALUES (3, 'Josef', 'Čapek', 'Povídání o pejskovy a kočičce');
INSERT INTO `autor`.`autor` (`idautor`, `jmeno`, `prijmeni`, `dilo`) VALUES (4, 'Karel', 'Čapek', 'Bílá nemoc');
INSERT INTO `autor`.`autor` (`idautor`, `jmeno`, `prijmeni`, `dilo`) VALUES (5, 'Karel', 'Čapek', 'R.U.R.');
INSERT INTO `autor`.`autor` (`idautor`, `jmeno`, `prijmeni`, `dilo`) VALUES (6, 'Božena', 'Němcová', 'Divá Bára');
INSERT INTO `autor`.`autor` (`idautor`, `jmeno`, `prijmeni`, `dilo`) VALUES (7, 'Božena', 'Němcová', 'V zámku a podzámčí');
INSERT INTO `autor`.`autor` (`idautor`, `jmeno`, `prijmeni`, `dilo`) VALUES (8, 'Joanne', 'Rowlingová', 'Harry Potter a Kámen mudrců');
INSERT INTO `autor`.`autor` (`idautor`, `jmeno`, `prijmeni`, `dilo`) VALUES (9, 'Bohumil', 'Hrabal', 'Obsluhoval jsem anglického krále');
INSERT INTO `autor`.`autor` (`idautor`, `jmeno`, `prijmeni`, `dilo`) VALUES (10, 'Victor', 'Hugo', 'Chrám Matky Boží v Paříži');

COMMIT;

